//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DarkGust : Character
{
	private float hauntPower
	{
		get;
		set;
	}

	public virtual void Haunt()
	{
		throw new System.NotImplementedException();
	}

}

