//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FloatingStairs : FloatObject
{
	public virtual object float Height
	{
		get;
		set;
	}

	public virtual object float Width
	{
		get;
		set;
	}

	public virtual object float StepHeight
	{
		get;
		set;
	}

	public virtual void void CreateStairs()
	{
		throw new System.NotImplementedException();
	}

}

