//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class HeavyObject
{
	public virtual object BoxCollider2D windBloackZone
	{
		get;
		set;
	}

	public virtual void void MoveObject()
	{
		throw new System.NotImplementedException();
	}

}

