//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LeverPad
{
	public virtual object WindPad[] connectedWindPads
	{
		get;
		set;
	}

	public virtual WindPad WindPad
	{
		get;
		set;
	}

	public virtual void void ActivateWindPad()
	{
		throw new System.NotImplementedException();
	}

}

