//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Selena : Character
{
	private object float windPower
	{
		get;
		set;
	}

	public virtual void void CastWindCone()
	{
		throw new System.NotImplementedException();
	}

	public virtual void void ChannelWind()
	{
		throw new System.NotImplementedException();
	}

	public virtual void void LiftObject()
	{
		throw new System.NotImplementedException();
	}

}

