//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class WindObject
{
	private object float windForce
	{
		get;
		set;
	}

	private object float windSpeed
	{
		get;
		set;
	}

	private object Vector3 windDirection
	{
		get;
		set;
	}

	public virtual object BoxCollider2D windTrigger
	{
		get;
		set;
	}

	public virtual void void ApplyWindPhysics()
	{
		throw new System.NotImplementedException();
	}

}

